### ISSUE TITLE
Examples / Details for the Source and Sink implementations

### ISSUE THREAD

**Issue by sanjaybharadwaj** [dbeck/minions_rs#5]
Hi David,

The library is very interesting, I am trying to create an antivirus sort of an application which is basically continuously searching for some patterns and then reporting it to a server. So I am planning to use the 'Source' actor for the part which is continuously monitoring based on continuous poll based scheduling and the server as a 'Sink' actor to keep receiving the attack information.

I am trying to understand the library, I see that there is a 'Process' trait which has to be implemented in both the cases, How do I send a specific information to the Sink? I do not find any detailed examples. Could you please provide me examples for the above mentioned scenario?

Thank you in anticipation of your response,
Best Regards,
Sanjay

**Comment by dbeck** [comment]
Hi Sanjay,

I wrote an article recently about it: http://dbeck.github.io/Example-Source-and-Sink/

Please don’t hesitate to ping me if it needs further clarification.

Best regards, David

**Comment by sanjaybharadwaj** [comment]
Hi David,

I do not have access to this link or the link is expired. Could you please check that?

Thank you and regards,
Sanjay

**Comment by dbeck** [comment]
This seems to be a temporary glitch in github pages. Can you please retry?

Kind regards,
David
1. nov. 22. de. 8:32 ezt írta ("sanjaybharadwaj" <
   notifications@github.com>):

**Comment by sanjaybharadwaj** [comment]
Hi David, 

Rust is really irritating :D I tried some code, I get this error "cannot move out of borrowed content", I did not understand the solutions in StackOverflow.

I am trying to implement an Actor that continuously keeps checking for the CPU usage of the system processes and then if the value reaches a limit, then I would like to report it to the sink.

I am trying to send the AttackInfo from the source to sink, the code is here [sec_agent.rs.txt](https://github.com/dbeck/acto-rs/files/611883/sec_agent.rs.txt)

Some other questions I have are
1. Is it possible to schedule source continuously without using the loop? but by using the `SchedulingRule::Loop` ?

2. On the sink side, I would like to have the value that is sent and I have to now transfer it via sockets using ip communication, do you know how can we do this?

Please let me know

Thank you in anticipation of your response,
Best Regards,
Sanjay

**Comment by dbeck** [comment]
Hi Sanjay,

Yes, the purpose of SchedulingRule::Loop is exactly that. You don’t need the loop afterwards. The other possibility is to use the periodic scheduling rule, which runs it periodically and continuously, every x microseconds.

For the CPU usage monitor, I would use the periodic rule and set the period to some reasonable value like 100000 usec. (100 ms)

I notice that  right now the state of your actors is AttackInfo and the message passed between them is also AttackInfo. I would probably try to separate what their state is and what they tell to each other. Ignore this suggestion if doesn’t make sense for your use-case.

As for your second question, I cannot tell. I would need more context.

Best regards, David

**Comment by sanjaybharadwaj** [comment]
Hi David,

What is the state of Actor? do you have some documentation? the only reference I have is the ReadME file of https://github.com/dbeck/acto-rs.

Are the content inside the structure is the status? where shall I define the sharing / communication messages?

Best Regards, Sanjay

**Comment by dbeck** [comment]
Hi Sanjay,

The state of the actor is what you have inside the DetectAttack and PrintAttack structs as members.

The type of the messages are defined in the OutputVale associated type in the Source trait implementation, and InputValue in case of Sink.

Hope this helps, David

**Comment by sanjaybharadwaj** [comment]
Hi David,

Is the behavior of the Scheduling rule Loop predictable? I found that the program terminates after random iterations and do not stay in indefinite loop.

` let mut detect_id = sched.add_task(detect_task, SchedulingRule::Loop).unwrap();`

Thank you and regards, Sanjay

**Comment by dbeck** [comment]
Hi Sanjay

What does the main thread do in the meanwhile?

If the scheduler goes out of scope, then it stops.

Best regards, David

sent from my too smart phone.
sorry for the typos.

2016. dec. 2. de. 7:14 ezt írta ("sanjaybharadwaj" <notifications@github.com

**Comment by sanjaybharadwaj** [comment]
Hi David,

Thank you for the information, Yes the main thread was exiting. 

Best Regards, Sanjay
