### ISSUE TITLE
update crates.io to show that minions has been renamed to acto-rs

### ISSUE THREAD

**Issue by Eh2406** [dbeck/minions_rs#6]
If rust/pull/44287 lands then [cargobomb](https://github.com/rust-lang/rust/pull/44287#issuecomment-329089956) tells us that the latest version of minions will have a type ambiguity error. `minions` is superseded by `acto-rs` which does not have this error, so I don't think any code needs to change.

[minions crates.io](https://crates.io/crates/minions) does not mention the the rename. Maybe the description should be change to make the deprecation explicit?

**Comment by dbeck** [comment]
The older minions lib is not maintained at all. If I could get rid of it easily I would do that. Any suggestions are very welcome.

**Comment by Eh2406** [comment]
I don't think that there is a way to delete it. I think the best you can do is push a new version with a description that makes it clear that it is deprecated in favor of acto-rs.

**Comment by dbeck** [comment]
This is now done
